export enum AriaRole {
	ALERT = 'alert', // A type of live region with important, and usually time-sensitive, information. See related alertdialog and status. https://www.w3.org/TR/wai-aria-1.2/#alert
	ALERT_DIALOG = 'alertdialog', // A type of dialog that contains an alert message, where initial focus goes to an element within the dialog. See related alert and dialog. https://www.w3.org/TR/wai-aria-1.2/#alertdialog
	APPLICATION = 'application', // A structure containing one or more focusable elements requiring user input, such as keyboard or gesture events, that do not follow a standard interaction pattern supported by a widget role. https://www.w3.org/TR/wai-aria-1.2/#application
	ARTICLE = 'article', // A section of a page that consists of a composition that forms an independent part of a document, page, or site. https://www.w3.org/TR/wai-aria-1.2/#article
	BANNER = 'banner', // A landmark that contains mostly site-oriented content, rather than page-specific content. https://www.w3.org/TR/wai-aria-1.2/#banner
	BLOCKQUOTE = 'blockquote', // A section of content that is quoted from another source. https://www.w3.org/TR/wai-aria-1.2/#blockquote
	BUTTON = 'button', // An input that allows for user-triggered actions when clicked or pressed. See related link. https://www.w3.org/TR/wai-aria-1.2/#button
	CAPTION = 'caption', // Visible content that names, and may also describe, a figure, table, grid, or treegrid. https://www.w3.org/TR/wai-aria-1.2/#caption
	CELL = 'cell', // A cell in a tabular container. See related gridcell. https://www.w3.org/TR/wai-aria-1.2/#cell
	CHECKBOX = 'checkbox', // A checkable input that has three possible values: true, false, or mixed. https://www.w3.org/TR/wai-aria-1.2/#checkbox
	CODE = 'code', // A section whose content represents a fragment of computer code. https://www.w3.org/TR/wai-aria-1.2/#code
	COLUMN_HEADER = 'columnheader', // A cell containing header information for a column. https://www.w3.org/TR/wai-aria-1.2/#columnheader
	COMBOBOX = 'combobox', // An input that controls another element, such as a listbox or grid, that can dynamically pop up to help the user set the value of the input. https://www.w3.org/TR/wai-aria-1.2/#combobox
	COMPLEMENTARY = 'complementary', // A landmark that is designed to be complementary to the main content at a similar level in the DOM hierarchy, but remaining meaningful when separated from the main content. https://www.w3.org/TR/wai-aria-1.2/#complementary
	CONTENT_INFO = 'contentinfo', // A landmark that contains information about the parent document. https://www.w3.org/TR/wai-aria-1.2/#contentinfo
	DEFINITION = 'definition', // A definition of a term or concept. See related term. https://www.w3.org/TR/wai-aria-1.2/#definition
	DELETION = 'deletion', // A deletion contains content that is marked as removed or content that is being suggested for removal. See related insertion. https://www.w3.org/TR/wai-aria-1.2/#deletion
	DIALOG = 'dialog', // A dialog is a descendant window of the primary window of a web application. For HTML pages, the primary application window is the entire web document, i.e., the body element. https://www.w3.org/TR/wai-aria-1.2/#deletion
	DOCUMENT = 'document', // An element containing content that assistive technology users may want to browse in a reading mode. https://www.w3.org/TR/wai-aria-1.2/#document
	EMPHASIS = 'emphasis', // One or more emphasized characters. See related strong. https://www.w3.org/TR/wai-aria-1.2/#emphasis
	FEED = 'feed', // A scrollable list of articles where scrolling may cause articles to be added to or removed from either end of the list. https://www.w3.org/TR/wai-aria-1.2/#feed
	FIGURE = 'figure', // A perceivable section of content that typically contains a graphical document, images, code snippets, or example text. The parts of a figure MAY be user-navigable. https://www.w3.org/TR/wai-aria-1.2/#figure
	FORM = 'form', // A landmark region that contains a collection of items and objects that, as a whole, combine to create a form. See related search. https://www.w3.org/TR/wai-aria-1.2/#form
	GENERIC = 'generic', // A nameless container element that has no semantic meaning on its own. https://www.w3.org/TR/wai-aria-1.2/#generic
	GRID = 'grid', // A composite widget containing a collection of one or more rows with one or more cells where some or all cells in the grid are focusable by using methods of two-dimensional navigation, such as directional arrow keys. https://www.w3.org/TR/wai-aria-1.2/#grid
	GRID_CELL = 'gridcell', // A cell in a grid or treegrid. https://www.w3.org/TR/wai-aria-1.2/#gridcell
	GROUP = 'group', // A set of user interface objects that is not intended to be included in a page summary or table of contents by assistive technologies. https://www.w3.org/TR/wai-aria-1.2/#group
	HEADING = 'heading', // A heading for a section of the page. https://www.w3.org/TR/wai-aria-1.2/#heading
	IMG = 'img', // A container for a collection of elements that form an image. https://www.w3.org/TR/wai-aria-1.2/#img
	INSERTION = 'insertion', // An insertion contains content that is marked as added or content that is being suggested for addition. See related deletion. https://www.w3.org/TR/wai-aria-1.2/#insertion
	LINK = 'link', // An interactive reference to an internal or external resource that, when activated, causes the user agent to navigate to that resource. See related button. https://www.w3.org/TR/wai-aria-1.2/#link
	LIST = 'list', // A section containing listitem elements. See related listbox. https://www.w3.org/TR/wai-aria-1.2/#list
	LISTBOX = 'listbox', // A widget that allows the user to select one or more items from a list of choices. See related combobox and list. https://www.w3.org/TR/wai-aria-1.2/#listbox
	LIST_ITEM = 'listitem', // A single item in a list or directory. https://www.w3.org/TR/wai-aria-1.2/#listitem
	LOG = 'log', // A type of live region where new information is added in meaningful order and old information may disappear. See related marquee. https://www.w3.org/TR/wai-aria-1.2/#log
	MAIN = 'main', // A landmark containing the main content of a document. https://www.w3.org/TR/wai-aria-1.2/#main
	MARQUEE = 'marquee', // A type of live region where non-essential information changes frequently. See related log. https://www.w3.org/TR/wai-aria-1.2/#marquee
	MATH = 'math', // Content that represents a mathematical expression. https://www.w3.org/TR/wai-aria-1.2/#math
	METER = 'meter', // An element that represents a scalar measurement within a known range, or a fractional value. See related progressbar. https://www.w3.org/TR/wai-aria-1.2/#meter
	MENU = 'menu', // A type of widget that offers a list of choices to the user. https://www.w3.org/TR/wai-aria-1.2/#menu
	MENUBAR = 'menubar', // A presentation of menu that usually remains visible and is usually presented horizontally. https://www.w3.org/TR/wai-aria-1.2/#menubar
	MENU_ITEM = 'menuitem', // An option in a set of choices contained by a menu or menubar. https://www.w3.org/TR/wai-aria-1.2/#menuitem
	MENU_ITEM_CHECKBOX = 'menuitemcheckbox', // A menuitem with a checkable state whose possible values are true, false, or mixed. https://www.w3.org/TR/wai-aria-1.2/#menuitemcheckbox
	MENU_ITEM_RADIO = 'menuitemradio', // A checkable menuitem in a set of elements with the same role, only one of which can be checked at a time. https://www.w3.org/TR/wai-aria-1.2/#menuitemradio
	NAVIGATION = 'navigation', // A landmark containing a collection of navigational elements (usually links) for navigating the document or related documents. https://www.w3.org/TR/wai-aria-1.2/#navigation
	NONE = 'none', // An element whose implicit native role semantics will not be mapped to the accessibility API. See synonym presentation. https://www.w3.org/TR/wai-aria-1.2/#none
	NOTE = 'note', // A section whose content is parenthetic or ancillary to the main content of the resource. https://www.w3.org/TR/wai-aria-1.2/#none
	OPTION = 'option', // A selectable item in a listbox. https://www.w3.org/TR/wai-aria-1.2/#option
	PARAGRAPH = 'paragraph', // A paragraph of content. https://www.w3.org/TR/wai-aria-1.2/#paragraph
	PRESENTATION = 'presentation', // An element whose implicit native role semantics will not be mapped to the accessibility API. See synonym none. https://www.w3.org/TR/wai-aria-1.2/#presentation
	PROGRESSBAR = 'progressbar', // An element that displays the progress status for tasks that take a long time. https://www.w3.org/TR/wai-aria-1.2/#progressbar
	RADIO = 'radio', // A checkable input in a group of elements with the same role, only one of which can be checked at a time. https://www.w3.org/TR/wai-aria-1.2/#radio
	RADIO_GROUP = 'radiogroup', // A group of radio buttons. https://www.w3.org/TR/wai-aria-1.2/#radiogroup
	REGION = 'region', // A landmark containing content that is relevant to a specific, author-specified purpose and sufficiently important that users will likely want to be able to navigate to the section easily and to have it listed in a summary of the page. Such a page summary could be generated dynamically by a user agent or assistive technology. https://www.w3.org/TR/wai-aria-1.2/#region
	ROW = 'row', // A row of cells in a tabular container. https://www.w3.org/TR/wai-aria-1.2/#row
	ROW_GROUP = 'rowgroup', // A structure containing one or more row elements in a tabular container. https://www.w3.org/TR/wai-aria-1.2/#rowgroup
	ROW_HEADER = 'rowheader', // A cell containing header information for a row. https://www.w3.org/TR/wai-aria-1.2/#rowheader
	SCROLLBAR = 'scrollbar', // A graphical object that controls the scrolling of content within a viewing area, regardless of whether the content is fully displayed within the viewing area. https://www.w3.org/TR/wai-aria-1.2/#scrollbar
	SEARCH = 'search', // A landmark region that contains a collection of items and objects that, as a whole, combine to create a search facility. See related form and searchbox. https://www.w3.org/TR/wai-aria-1.2/#search
	SEARCHBOX = 'searchbox', // A type of textbox intended for specifying search criteria. See related textbox and search. https://www.w3.org/TR/wai-aria-1.2/#searchbox
	SEPARATOR = 'separator', // A divider that separates and distinguishes sections of content or groups of menuitems. https://www.w3.org/TR/wai-aria-1.2/#separator
	SLIDER = 'slider', // An input where the user selects a value from within a given range. https://www.w3.org/TR/wai-aria-1.2/#slider
	SPIN_BUTTON = 'spinbutton', // A form of range that expects the user to select from among discrete choices. https://www.w3.org/TR/wai-aria-1.2/#spinbutton
	STATUS = 'status', // A type of live region whose content is advisory information for the user but is not important enough to justify an alert, often but not necessarily presented as a status bar. https://www.w3.org/TR/wai-aria-1.2/#status
	STRONG = 'strong', // Content that is important, serious, or urgent. See related emphasis. https://www.w3.org/TR/wai-aria-1.2/#strong
	SUBSCRIPT = 'subscript', // One or more subscripted characters. See related superscript. https://www.w3.org/TR/wai-aria-1.2/#subscript
	SUPERSCRIPT = 'superscript', // One or more superscripted characters. See related superscript. https://www.w3.org/TR/wai-aria-1.2/#superscript
	SWITCH = 'switch', // A type of checkbox that represents on/off values, as opposed to checked/unchecked values. See related checkbox. https://www.w3.org/TR/wai-aria-1.2/#switch
	TAB = 'tab', // A grouping label providing a mechanism for selecting the tab content that is to be rendered to the user. https://www.w3.org/TR/wai-aria-1.2/#tab
	TABLE = 'table', // A section containing data arranged in rows and columns. See related grid. https://www.w3.org/TR/wai-aria-1.2/#table
	TAB_LIST = 'tablist', // A list of tab elements, which are references to tabpanel elements. https://www.w3.org/TR/wai-aria-1.2/#tablist
	TAB_PANEL = 'tabpanel', // A container for the resources associated with a tab, where each tab is contained in a tablist. https://www.w3.org/TR/wai-aria-1.2/#tabpanel
	TERM = 'term', // A word or phrase with a corresponding definition. See related definition. https://www.w3.org/TR/wai-aria-1.2/#term
	TEXTBOX = 'textbox', // A type of input that allows free-form text as its value. https://www.w3.org/TR/wai-aria-1.2/#textbox
	TIME = 'time', // An element that represents a specific point in time. https://www.w3.org/TR/wai-aria-1.2/#time
	TIMER = 'timer', // A type of live region containing a numerical counter which indicates an amount of elapsed time from a start point, or the time remaining until an end point. https://www.w3.org/TR/wai-aria-1.2/#timer
	TOOLBAR = 'toolbar', // A collection of commonly used function buttons or controls represented in compact visual form. https://www.w3.org/TR/wai-aria-1.2/#toolbar
	TOOLTIP = 'tooltip', // A contextual popup that displays a description for an element. https://www.w3.org/TR/wai-aria-1.2/#tooltip
	TREE = 'tree', // A widget that allows the user to select one or more items from a hierarchically organized collection. https://www.w3.org/TR/wai-aria-1.2/#tree
	TREE_GRID = 'treegrid', // A grid whose rows can be expanded and collapsed in the same manner as for a tree. https://www.w3.org/TR/wai-aria-1.2/#treegrid
	TREE_ITEM = 'treeitem', // An option item of a tree. This is an element within a tree that may be expanded or collapsed if it contains a sub-level group of tree item elements. https://www.w3.org/TR/wai-aria-1.2/#treeitem
}

export enum AutocompletionType {
	both = 'both',
	inline = 'inline',
	list = 'list',
	none = 'none',
}

export enum Calendar {
	buddhist = 'Thai Buddhist calendar',
	chinese = 'Traditional Chinese calendar',
	coptic = 'Coptic calendar',
	ethioaa = 'Ethiopic calendar, Amete Alem (epoch approx. 5493 B.C.E.)',
	ethiopic = 'Ethiopic calendar, Amete Mihret (epoch approx. 8 C.E.)',
	gregory = 'Gregorian calendar',
	hebrew = 'Traditional Hebrew calendar',
	indian = 'Indian calendar',
	islamic = 'Astronomical Arabic calendar',
	islamicc = 'Civil (algorithmic) Arabic calendar',
	iso8601 = 'ISO-8601 calendar',
	japanese = 'Japanese Imperial calendar (same as Gregorian except for the year, with one era for each Emperor)',
	persian = 'Persian calendar',
	roc = 'Republic of China calendar',
}

export enum FunctionalComponentType {
	Abbreviation = 'Abbreviation',
	Accordion = 'Accordion',
	Address = 'Address',
	Alert = 'Alert',
	Anchor = 'Anchor',
	Article = 'Article',
	Aside = 'Aside',
	Audio = 'Audio',
	Banner = 'Banner',
	Bibliography = 'Bibliography',
	BibliographyEntry = 'BibliographyEntry',
	Breadcrumb = 'Breadcrumb',
	Button = 'Button',
	ButtonGroup = 'ButtonGroup',
	Canvas = 'Canvas',
	Caption = 'Caption',
	Card = 'Card',
	CharacterCount = 'CharacterCount',
	Checkbox = 'Checkbox',
	Citation = 'Citation',
	Code = 'Code',
	CodeBlock = 'CodeBlock',
	Collection = 'Collection',
	ComboBox = 'ComboBox',
	DataVisualization = 'DataVisualization',
	DateInput = 'DateInput',
	DatePicker = 'DatePicker',
	DateRangePicker = 'DateRangePicker',
	DefinedTerm = 'DefinedTerm',
	Deletion = 'Deletion',
	Details = 'Details',
	Dialog = 'Dialog',
	Dropdown = 'Dropdown',
	EmailAddress = 'EmailAddress',
	Embed = 'Embed',
	Emphasize = 'Emphasize',
	Fieldset = 'Fieldset',
	Figure = 'Figure',
	FileInput = 'FileInput',
	FinePrint = 'FinePrint',
	Footer = 'Footer',
	Footnote = 'Footnote',
	ForeignTerm = 'ForeignTerm',
	Form = 'Form',
	FormattedTime = 'FormattedTime',
	FormattedDate = 'FormattedDate',
	FormattedDateTime = 'FormattedDateTime',
	Framer = 'Framer',
	Glossary = 'Glossary',
	GlossaryEntry = 'GlossaryEntry',
	Header = 'Header',
	Heading = 'Heading',
	Icon = 'Icon',
	Iconic = 'Iconic',
	IconList = 'IconList',
	Identifier = 'Identifier',
	Image = 'Image',
	InlineLink = 'InlineLink',
	InputPrefixOrSuffix = 'InputPrefixOrSuffix',
	Insertion = 'Insertion',
	ItemProp = 'ItemProp',
	ItemScope = 'ItemScope',
	Key = 'Key',
	KeyboardInput = 'KeyboardInput',
	Legend = 'Legend',
	Link = 'Link',
	List = 'List',
	ListItem = 'ListItem',
	Main = 'Main',
	Map = 'Map',
	MarkRelevant = 'MarkRelevant',
	Menu = 'Menu',
	Meter = 'Meter',
	Modal = 'Modal',
	Nav = 'Nav',
	Object = 'Object',
	Output = 'Output',
	Page = 'Page',
	Pagination = 'Pagination',
	Paragraph = 'Paragraph',
	Parameter = 'Parameter',
	PhoneNumber = 'PhoneNumber',
	Picture = 'Picture',
	Portal = 'Portal',
	PreformattedText = 'PreformattedText',
	ProcessList = 'ProcessList',
	ProgressBar = 'ProgressBar',
	Prose = 'Prose',
	PullQuote = 'PullQuote',
	Quotation = 'Quotation',
	RadioButtons = 'RadioButtons',
	RangeSlider = 'RangeSlider',
	Ruby = 'Ruby',
	Rule = 'Rule',
	Sample = 'Sample',
	Search = 'Search',
	Section = 'Section',
	SideNavigation = 'SideNavigation',
	SiteAlert = 'SiteAlert',
	Slot = 'Slot',
	SmallText = 'SmallText',
	Source = 'Source',
	StepIndicator = 'StepIndicator',
	Subscript = 'Subscript',
	Summary = 'Summary',
	SummaryBox = 'SummaryBox',
	Superscript = 'Superscript',
	Symbol = 'Symbol',
	Table = 'Table',
	Tag = 'Tag',
	TimePicker = 'TimePicker',
	Tooltip = 'Tooltip',
	Track = 'Track',
	Typography = 'Typography',
	Validation = 'Validation',
	Variable = 'Variable',
	Video = 'Video',
}

export enum WebComponentType {
	Box = 'box-bender',
	Center = 'center-bender',
	Cluster = 'cluster-bender',
	Cover = 'cover-bender',
	Frame = 'frame-bender',
	Grid = 'grid-bender',
	Reel = 'reel-bender',
	Sidebar = 'sidebar-bender',
	Stack = 'stack-bender',
	Switcher = 'switcher-bender',
	TextField = 'text-field-bender',
	Topper = 'topper-bender',
}

export type ComponentType = FunctionalComponentType | WebComponentType

export enum AbortSignalEvent {
	ABORT = 'abort',
}

export enum AudioScheduledSourceNodeEvent {
	ENDED = 'ended',
}

export enum AudioTrackListEvent {
	ADDTRACK = 'addtrack',
	CHANGE = 'change',
	REMOVETRACK = 'removetrack',
}

export enum BroadcastChannelEvent {
	MESSAGEERROR = 'messageerror',
	MESSAGE = 'message',
}

export enum DedicatedWorkerGlobalScopeEvent {
	MESSAGEERROR = 'messageerror',
	MESSAGE = 'message',
}

export enum DocumentEvent {
	ANIMATION_END = 'animationend',
	ANIMATION_ITERATION = 'animationiteration',
	ANIMATION_START = 'animationstart',
	COPY = 'copy',
	CUT = 'cut',
	DOM_CONTENT_LOADED = 'DOMContentLoaded',
	DRAG_END = 'dragend',
	DRAG_ENTER = 'dragenter',
	DRAG_LEAVE = 'dragleave',
	DRAG_OVER = 'dragover',
	DRAG_START = 'dragstart',
	DRAG = 'drag',
	DROP = 'drop',
	FULL_SCREEN_CHANGE = 'fullscreenchange',
	FULL_SCREEN_ERROR = 'fullscreenerror',
	GOT_POINTER_CAPTURE = 'gotpointercapture',
	KEY_DOWN = 'keydown',
	KEY_UP = 'keyup',
	LOST_POINTER_CAPTURE = 'lostpointercapture',
	PASTE = 'paste',
	POINTER_CANCEL = 'pointercancel',
	POINTER_DOWN = 'pointerdown',
	POINTER_ENTER = 'pointerenter',
	POINTER_LEAVE = 'pointerleave',
	POINTER_LOCK_CHANGE = 'pointerlockchange',
	POINTER_LOCK_ERROR = 'pointerlockerror',
	POINTER_MOVE = 'pointermove',
	POINTER_OUT = 'pointerout',
	POINTER_OVER = 'pointerover',
	POINTER_UP = 'pointerup',
	READY_STATE_CHANGE = 'readystatechange',
	SCROLL = 'scroll',
	SELECTION_CHANGE = 'selectionchange',
	SELECT_START = 'selectstart',
	TOUCH_CANCEL = 'touchcancel',
	TOUCH_END = 'touchend',
	TOUCH_MOVE = 'touchmove',
	TOUCH_START = 'touchstart',
	TRANSITION_END = 'transitionend',
	VISIBILITY_CHANGE = 'visibilitychange',
	WHEEL = 'wheel',
}

export enum ElementEvent {
	AUX_CLICK = 'auxclick',
	BLUR = 'blur',
	CLICK = 'click',
	COMPOSITION_END = 'compositionend',
	COMPOSITION_START = 'compositionstart',
	COMPOSITION_UPDATE = 'compositionupdate',
	CONTEXT_MENU = 'contextmenu',
	COPY = 'copy',
	CUT = 'cut',
	DBL_CLICK = 'dblclick',
	ERROR = 'error',
	FOCUS_IN = 'focusin',
	FOCUS_OUT = 'focusout',
	FOCUS = 'focus',
	FULL_SCREEN_CHANGE = 'fullscreenchange',
	FULL_SCREEN_ERROR = 'fullscreenerror',
	KEY_DOWN = 'keydown',
	KEY_UP = 'keyup',
	MOUSE_DOWN = 'mousedown',
	MOUSE_ENTER = 'mouseenter',
	MOUSE_LEAVE = 'mouseleave',
	MOUSE_MOVE = 'mousemove',
	MOUSE_OUT = 'mouseout',
	MOUSE_OVER = 'mouseover',
	MOUSE_UP = 'mouseup',
	PASTE = 'paste',
	SCROLL = 'scroll',
	SELECT = 'select',
	TOUCH_CANCEL = 'touchcancel',
	TOUCH_END = 'touchend',
	TOUCH_MOVE = 'touchmove',
	TOUCH_START = 'touchstart',
	WHEEL = 'wheel',
}

export enum EventSourceEvent {
	ERROR = 'error',
	MESSAGE = 'message',
	OPEN = 'open',
}

export enum FileReaderEvent {
	ABORT = 'abort',
	ERROR = 'error',
	LOAD_END = 'loadend',
	LOAD_START = 'loadstart',
	LOAD = 'load',
	PROGRESS = 'progress',
}

export enum HTMLCanvasElementEvent {
	WEB_GL_CONTEXT_CREATION_ERROR = 'webglcontextcreationerror',
	WEB_GL_CONTEXT_LOST = 'webglcontextlost',
	WEB_GL_CONTEXT_RESTORED = 'webglcontextrestored',
}

export enum HTMLDetailsElementEvent {
	TOGGLE = 'toggle',
}

export enum HTMLDialogElementEvent {
	CANCEL = 'cancel',
	CLOSE = 'close',
}

export enum HTMLElementEvent {
	ANIMATION_END = 'animationend',
	ANIMATION_ITERATION = 'animationiteration',
	ANIMATION_START = 'animationstart',
	BEFORE_INPUT = 'beforeinput',
	CHANGE = 'change',
	GOT_POINTER_CAPTURE = 'gotpointercapture',
	INPUT = 'input',
	LOST_POINTER_CAPTURE = 'lostpointercapture',
	POINTER_CANCEL = 'pointercancel',
	POINTER_DOWN = 'pointerdown',
	POINTER_ENTER = 'pointerenter',
	POINTER_LEAVE = 'pointerleave',
	POINTER_MOVE = 'pointermove',
	POINTER_OUT = 'pointerout',
	POINTER_OVER = 'pointerover',
	POINTER_UP = 'pointerup',
	TRANSITION_END = 'transitionend',
}

export enum HTMLFormElementEvent {
	FORM_DATA = 'formdata',
	RESET = 'reset',
	SUBMIT = 'submit',
}

export enum HTMLInputElementEvent {
	INVALID = 'invalid',
}

export enum HTMLMediaElementEvent {
	ABORT = 'abort',
	CAN_PLAY_THROUGH = 'canplaythrough',
	CAN_PLAY = 'canplay',
	DURATION_CHANGE = 'durationchange',
	EMPTIED = 'emptied',
	ENDED = 'ended',
	ERROR = 'error',
	LOADED_DATA = 'loadeddata',
	LOADED_METADATA = 'loadedmetadata',
	LOAD_START = 'loadstart',
	PAUSE = 'pause',
	PLAYING = 'playing',
	PLAY = 'play',
	PROGRESS = 'progress',
	RATE_CHANGE = 'ratechange',
	SEEKED = 'seeked',
	SEEKING = 'seeking',
	STALLED = 'stalled',
	SUSPEND = 'suspend',
	TIME_UPDATE = 'timeupdate',
	VOLUME_CHANGE = 'volumechange',
	WAITING = 'waiting',
}

export enum HTMLTrackElementEvent {
	CUE_CHANGE = 'cuechange',
}

export enum HTMLVideoElementEvent {
	ENTER_PICTURE_IN_PICTURE = 'enterpictureinpicture',
	LEAVE_PICTURE_IN_PICTURE = 'leavepictureinpicture',
}

export enum IDBDatabaseEvent {
	ABORT = 'abort',
	CLOSE = 'close',
	ERROR = 'error',
	VERSION_CHANGE = 'versionchange',
}

export enum IDBOpenDBRequestEvent {
	BLOCKED = 'blocked',
	UPGRADE_NEEDED = 'upgradeneeded',
}

export enum IDBRequestEvent {
	ERROR = 'error',
	SUCCESS = 'success',
}

export enum IDBTransactionEvent {
	ABORT = 'abort',
	COMPLETE = 'complete',
	ERROR = 'error',
}

export enum MediaDevicesEvent {
	DEVICE_CHANGE = 'devicechange',
}

export enum MediaRecorderEvent {
	ERROR = 'error',
}

export enum MediaStreamEvent {
	ADD_TRACK = 'addtrack',
	REMOVE_TRACK = 'removetrack',
}

export enum MediaStreamTrackEvent {
	ENDED = 'ended',
	MUTE = 'mute',
	UNMUTE = 'unmute',
}

export enum MessagePortEvent {
	MESSAGE_ERROR = 'messageerror',
	MESSAGE = 'message',
}

export enum OfflineAudioContextEvent {
	COMPLETE = 'complete',
}

export enum PaymentRequestEvent {
	PAYMENT_METHOD_CHANGE = 'paymentmethodchange',
}

export enum PerformanceEvent {
	RESOURCE_TIMING_BUFFER_FULL = 'resourcetimingbufferfull',
}

export enum PictureInPictureWindowEvent {
	RESIZE = 'resize',
}

export enum RTCDataChannelEvent {
	BUFFERED_AMOUNT_LOW = 'bufferedamountlow',
	CLOSE = 'close',
	ERROR = 'error',
	MESSAGE = 'message',
	OPEN = 'open',
}

export enum RTCDtlsTransportEvent {
	ERROR = 'error',
}

export enum RTCDTMFSenderEvent {
	TONE_CHANGE = 'tonechange',
}

export enum RTCIceTransportEvent {
	GATHERING_STATE_CHANGE = 'gatheringstatechange',
	SELECTED_CANDIDATE_PAIR_CHANGE = 'selectedcandidatepairchange',
	STATE_CHANGE = 'statechange',
}

export enum RTCPeerConnectionEvent {
	CONNECTION_STATE_CHANGE = 'connectionstatechange',
	DATA_CHANNEL = 'datachannel',
	ICE_CANDIDATE_ERROR = 'icecandidateerror',
	ICE_CANDIDATE = 'icecandidate',
	ICE_CONNECTION_STATE_CHANGE = 'iceconnectionstatechange',
	ICE_GATHERING_STATE_CHANGE = 'icegatheringstatechange',
	NEGOTIATION_NEEDED = 'negotiationneeded',
	SIGNALING_STATE_CHANGE = 'signalingstatechange',
	TRACK = 'track',
}

export enum ServiceWorkerContainerEvent {
	MESSAGE = 'message',
}

export enum ServiceWorkerGlobalScopeEvent {
	ACTIVATE = 'activate',
	CONTENT_DELETE = 'contentdelete',
	INSTALL = 'install',
	MESSAGE = 'message',
	NOTIFICATION_CLICK = 'notificationclick',
	PUSH_SUBSCRIPTION_CHANGE = 'pushsubscriptionchange',
	PUSH = 'push',
}

export enum SharedWorkerGlobalScopeEvent {
	CONNECT = 'connect',
}

// Experimental tech
/*
export enum SpeechRecognitionEvent {
	AUDIOEND = 'audioend',
	AUDIOSTART = 'audiostart',
	END = 'end',
	ERROR = 'error',
	NOMATCH = 'nomatch',
	RESULT = 'result',
	SOUNDEND = 'soundend',
	SOUNDSTART = 'soundstart',
	SPEECHEND = 'speechend',
	SPEECHSTART = 'speechstart',
	START = 'start',
}

export enum SpeechSynthesisEvent {
	VOICES_CHANGED = 'voiceschanged',
}

export enum SpeechSynthesisUtteranceEvent {
	BOUNDARY = 'boundary',
	END = 'end',
	ERROR = 'error',
	MARK = 'mark',
	PAUSE = 'pause',
	RESUME = 'resume',
	START = 'start',
}
*/

export enum SVGAnimationElementEvent {
	BEGIN_EVENT = 'beginEvent',
	END_EVENT = 'endEvent',
	REPEAT_EVENT = 'repeatEvent',
}

export enum SVGElementEvent {
	ABORT = 'abort',
	ERROR = 'error',
	LOAD = 'load',
	RESIZE = 'resize',
	SCROLL = 'scroll',
	UNLOAD = 'unload',
}

export enum SVGGraphicsElementEvent {
	COPY = 'copy',
	CUT = 'cut',
	PASTE = 'paste',
}

export enum TextTrackEvent {
	CUE_CHANGE = 'cuechange',
}

export enum TextTrackListEvent {
	ADD_TRACK = 'addtrack',
	CHANGE = 'change',
	REMOVE_TRACK = 'removeTrack',
}

export enum VideoTrackListEvent {
	ADD_TRACK = 'addtrack',
	CHANGE = 'change',
	REMOVE_TRACK = 'removeTrack',
}

export enum VisualViewportEvent {
	RESIZE = 'resize',
	SCROLL = 'scroll',
}

export enum WebSocketEvent {
	CLOSE = 'close',
	ERROR = 'error',
	MESSAGE = 'message',
	OPEN = 'open',
}

export enum WindowEvent {
	AFTER_PRINT = 'afterprint',
	// ANIMATION_CANCEL = 'animationcancel', // Experimental
	ANIMATION_END = 'animationend',
	ANIMATION_ITERATION = 'animationiteration',
	ANIMATION_START = 'animationstart',
	BEFORE_PRINT = 'beforeprint',
	BEFORE_UNLOAD = 'beforeunload',
	BLUR = 'blur',
	COPY = 'copy',
	CUT = 'cut',
	DEVICE_MOTION = 'devicemotion',
	DEVICE_ORIENTATION = 'deviceorientation',
	DOM_CONTENT_LOADED = 'DOMContentLoaded',
	ERROR = 'error',
	FOCUS = 'focus',
	GAME_PAD_CONNECTED = 'gamepadconnected',
	GAME_PAD_DISCONNECTED = 'gamepaddisconnected',
	HASH_CHANGE = 'hashchange',
	LANGUAGE_CHANGE = 'languagechange',
	LOAD = 'load',
	MESSAGE_ERROR = 'messageerror',
	MESSAGE = 'message',
	OFFLINE = 'offline',
	ONLINE = 'online',
	PAGE_HIDE = 'pagehide',
	PAGE_SHOW = 'pageshow',
	PASTE = 'paste',
	POP_STATE = 'popstate',
	REJECTION_HANDLED = 'rejectionhandled',
	RESIZE = 'resize',
	STORAGE = 'storage',
	// TRANSITION_CANCEL = 'transitioncancel', // Experimental
	TRANSITION_END = 'transitionend',
	// TRANSITION_RUN = 'transitionrun', // Experimental
	// TRANSITION_START = 'transitionstart', // Experimental
	UNHANDLED_REJECTION = 'unhandledrejection',
	UNLOAD = 'unload',
}

export enum WorkerEvent {
	MESSAGE_ERROR = 'messageerror',
	MESSAGE = 'message',
}

export enum WorkerGlobalScopeEvent {
	LANGUAGE_CHANGE = 'languagechange',
}

export enum XMLHttpRequestEvent {
	ABORT = 'abort',
	ERROR = 'error',
	LOAD_END = 'loadend',
	LOAD_START = 'loadstart',
	LOAD = 'load',
	PROGRESS = 'progress',
	TIMEOUT = 'timeout',
}

export enum XRReferenceSpaceEvent {
	RESET = 'reset',
}

export enum XRSessionEvent {
	END = 'end',
	INPUT_SOURCES_CHANGE = 'inputsourceschange',
	SELECT_END = 'selectend',
	SELECT_START = 'selectstart',
	SELECT = 'select',
	SQUEEZE_END = 'squeezeend',
	SQUEEZE_START = 'squeezestart',
	SQUEEZE = 'squeeze',
	VISIBILITY_CHANGE = 'visibilitychange',
}

export enum XRSystemEvent {
	DEVICE_CHANGE = 'devicechange',
}

export enum HighlightColor {
	YELLOW = 'yellow',
}

export enum PopupType {
	dialog = 'dialog',
	grid = 'grid',
	listbox = 'listbox',
	menu = 'menu',
	tree = 'tree',
}

export enum TimeZone {
	AFRICA_ABIDJAN = 'Africa/Abidjan',
	AFRICA_ACCRA = 'Africa/Accra',
	AFRICA_ADDIS_ABABA = 'Africa/Addis_Ababa',
	AFRICA_ALGIERS = 'Africa/Algiers',
	AFRICA_ASMARA = 'Africa/Asmara',
	AFRICA_BAMAKO = 'Africa/Bamako',
	AFRICA_BANGUI = 'Africa/Bangui',
	AFRICA_BANJUL = 'Africa/Banjul',
	AFRICA_BISSAU = 'Africa/Bissau',
	AFRICA_BLANTYRE = 'Africa/Blantyre',
	AFRICA_BRAZZAVILLE = 'Africa/Brazzaville',
	AFRICA_BUJUMBURA = 'Africa/Bujumbura',
	AFRICA_CAIRO = 'Africa/Cairo',
	AFRICA_CASABLANCA = 'Africa/Casablanca',
	AFRICA_CEUTA = 'Africa/Ceuta',
	AFRICA_CONAKRY = 'Africa/Conakry',
	AFRICA_DAKAR = 'Africa/Dakar',
	AFRICA_DAR_ES_SALAAM = 'Africa/Dar_es_Salaam',
	AFRICA_DJIBOUTI = 'Africa/Djibouti',
	AFRICA_DOUALA = 'Africa/Douala',
	AFRICA_EL_AAIUN = 'Africa/El_Aaiun',
	AFRICA_FREETOWN = 'Africa/Freetown',
	AFRICA_GABORONE = 'Africa/Gaborone',
	AFRICA_HARARE = 'Africa/Harare',
	AFRICA_JOHANNESBURG = 'Africa/Johannesburg',
	AFRICA_JUBA = 'Africa/Juba',
	AFRICA_KAMPALA = 'Africa/Kampala',
	AFRICA_KHARTOUM = 'Africa/Khartoum',
	AFRICA_KIGALI = 'Africa/Kigali',
	AFRICA_KINSHASA = 'Africa/Kinshasa',
	AFRICA_LAGOS = 'Africa/Lagos',
	AFRICA_LIBREVILLE = 'Africa/Libreville',
	AFRICA_LOME = 'Africa/Lome',
	AFRICA_LUANDA = 'Africa/Luanda',
	AFRICA_LUBUMBASHI = 'Africa/Lubumbashi',
	AFRICA_LUSAKA = 'Africa/Lusaka',
	AFRICA_MALABO = 'Africa/Malabo',
	AFRICA_MAPUTO = 'Africa/Maputo',
	AFRICA_MASERU = 'Africa/Maseru',
	AFRICA_MBABANE = 'Africa/Mbabane',
	AFRICA_MOGADISHU = 'Africa/Mogadishu',
	AFRICA_MONROVIA = 'Africa/Monrovia',
	AFRICA_NAIROBI = 'Africa/Nairobi',
	AFRICA_NDJAMENA = 'Africa/Ndjamena',
	AFRICA_NIAMEY = 'Africa/Niamey',
	AFRICA_NOUAKCHOTT = 'Africa/Nouakchott',
	AFRICA_OUAGADOUGOU = 'Africa/Ouagadougou',
	AFRICA_PORTO_NOVO = 'Africa/Porto-Novo',
	AFRICA_SAO_TOME = 'Africa/Sao_Tome',
	AFRICA_TRIPOLI = 'Africa/Tripoli',
	AFRICA_TUNIS = 'Africa/Tunis',
	AFRICA_WINDHOEK = 'Africa/Windhoek',
	AMERICA_ADAK = 'America/Adak',
	AMERICA_ANCHORAGE = 'America/Anchorage',
	AMERICA_ANGUILLA = 'America/Anguilla',
	AMERICA_ANTIGUA = 'America/Antigua',
	AMERICA_ARAGUAINA = 'America/Araguaina',
	AMERICA_ARGENTINA_BUENOS_AIRES = 'America/Argentina/Buenos_Aires',
	AMERICA_ARGENTINA_CATAMARCA = 'America/Argentina/Catamarca',
	AMERICA_ARGENTINA_CORDOBA = 'America/Argentina/Cordoba',
	AMERICA_ARGENTINA_JUJUY = 'America/Argentina/Jujuy',
	AMERICA_ARGENTINA_LA_RIOJA = 'America/Argentina/La_Rioja',
	AMERICA_ARGENTINA_MENDOZA = 'America/Argentina/Mendoza',
	AMERICA_ARGENTINA_RIO_GALLEGOS = 'America/Argentina/Rio_Gallegos',
	AMERICA_ARGENTINA_SALTA = 'America/Argentina/Salta',
	AMERICA_ARGENTINA_SAN_JUAN = 'America/Argentina/San_Juan',
	AMERICA_ARGENTINA_SAN_LUIS = 'America/Argentina/San_Luis',
	AMERICA_ARGENTINA_TUCUMAN = 'America/Argentina/Tucuman',
	AMERICA_ARGENTINA_USHUAIA = 'America/Argentina/Ushuaia',
	AMERICA_ARUBA = 'America/Aruba',
	AMERICA_ASUNCION = 'America/Asuncion',
	AMERICA_ATIKOKAN = 'America/Atikokan',
	AMERICA_BAHIA = 'America/Bahia',
	AMERICA_BAHIA_BANDERAS = 'America/Bahia_Banderas',
	AMERICA_BARBADOS = 'America/Barbados',
	AMERICA_BELEM = 'America/Belem',
	AMERICA_BELIZE = 'America/Belize',
	AMERICA_BLANC_SABLON = 'America/Blanc-Sablon',
	AMERICA_BOA_VISTA = 'America/Boa_Vista',
	AMERICA_BOGOTA = 'America/Bogota',
	AMERICA_BOISE = 'America/Boise',
	AMERICA_CAMBRIDGE_BAY = 'America/Cambridge_Bay',
	AMERICA_CAMPO_GRANDE = 'America/Campo_Grande',
	AMERICA_CANCUN = 'America/Cancun',
	AMERICA_CARACAS = 'America/Caracas',
	AMERICA_CAYENNE = 'America/Cayenne',
	AMERICA_CAYMAN = 'America/Cayman',
	AMERICA_CHICAGO = 'America/Chicago',
	AMERICA_CHIHUAHUA = 'America/Chihuahua',
	AMERICA_COSTA_RICA = 'America/Costa_Rica',
	AMERICA_CRESTON = 'America/Creston',
	AMERICA_CUIABA = 'America/Cuiaba',
	AMERICA_CURACAO = 'America/Curacao',
	AMERICA_DANMARKSHAVN = 'America/Danmarkshavn',
	AMERICA_DAWSON = 'America/Dawson',
	AMERICA_DAWSON_CREEK = 'America/Dawson_Creek',
	AMERICA_DENVER = 'America/Denver',
	AMERICA_DETROIT = 'America/Detroit',
	AMERICA_DOMINICA = 'America/Dominica',
	AMERICA_EDMONTON = 'America/Edmonton',
	AMERICA_EIRUNEPE = 'America/Eirunepe',
	AMERICA_EL_SALVADOR = 'America/El_Salvador',
	AMERICA_FORT_NELSON = 'America/Fort_Nelson',
	AMERICA_FORTALEZA = 'America/Fortaleza',
	AMERICA_GLACE_BAY = 'America/Glace_Bay',
	AMERICA_GOOSE_BAY = 'America/Goose_Bay',
	AMERICA_GRAND_TURK = 'America/Grand_Turk',
	AMERICA_GRENADA = 'America/Grenada',
	AMERICA_GUADELOUPE = 'America/Guadeloupe',
	AMERICA_GUATEMALA = 'America/Guatemala',
	AMERICA_GUAYAQUIL = 'America/Guayaquil',
	AMERICA_GUYANA = 'America/Guyana',
	AMERICA_HALIFAX = 'America/Halifax',
	AMERICA_HAVANA = 'America/Havana',
	AMERICA_HERMOSILLO = 'America/Hermosillo',
	AMERICA_INDIANA_INDIANAPOLIS = 'America/Indiana/Indianapolis',
	AMERICA_INDIANA_KNOX = 'America/Indiana/Knox',
	AMERICA_INDIANA_MARENGO = 'America/Indiana/Marengo',
	AMERICA_INDIANA_PETERSBURG = 'America/Indiana/Petersburg',
	AMERICA_INDIANA_TELL_CITY = 'America/Indiana/Tell_City',
	AMERICA_INDIANA_VEVAY = 'America/Indiana/Vevay',
	AMERICA_INDIANA_VINCENNES = 'America/Indiana/Vincennes',
	AMERICA_INDIANA_WINAMAC = 'America/Indiana/Winamac',
	AMERICA_INUVIK = 'America/Inuvik',
	AMERICA_IQALUIT = 'America/Iqaluit',
	AMERICA_JAMAICA = 'America/Jamaica',
	AMERICA_JUNEAU = 'America/Juneau',
	AMERICA_KENTUCKY_LOUISVILLE = 'America/Kentucky/Louisville',
	AMERICA_KENTUCKY_MONTICELLO = 'America/Kentucky/Monticello',
	AMERICA_KRALENDIJK = 'America/Kralendijk',
	AMERICA_LA_PAZ = 'America/La_Paz',
	AMERICA_LIMA = 'America/Lima',
	AMERICA_LOS_ANGELES = 'America/Los_Angeles',
	AMERICA_LOWER_PRINCES = 'America/Lower_Princes',
	AMERICA_MACEIO = 'America/Maceio',
	AMERICA_MANAGUA = 'America/Managua',
	AMERICA_MANAUS = 'America/Manaus',
	AMERICA_MARIGOT = 'America/Marigot',
	AMERICA_MARTINIQUE = 'America/Martinique',
	AMERICA_MATAMOROS = 'America/Matamoros',
	AMERICA_MAZATLAN = 'America/Mazatlan',
	AMERICA_MENOMINEE = 'America/Menominee',
	AMERICA_MERIDA = 'America/Merida',
	AMERICA_METLAKATLA = 'America/Metlakatla',
	AMERICA_MEXICO_CITY = 'America/Mexico_City',
	AMERICA_MIQUELON = 'America/Miquelon',
	AMERICA_MONCTON = 'America/Moncton',
	AMERICA_MONTERREY = 'America/Monterrey',
	AMERICA_MONTEVIDEO = 'America/Montevideo',
	AMERICA_MONTSERRAT = 'America/Montserrat',
	AMERICA_NASSAU = 'America/Nassau',
	AMERICA_NEW_YORK = 'America/New_York',
	AMERICA_NIPIGON = 'America/Nipigon',
	AMERICA_NOME = 'America/Nome',
	AMERICA_NORONHA = 'America/Noronha',
	AMERICA_NORTH_DAKOTA_BEULAH = 'America/North_Dakota/Beulah',
	AMERICA_NORTH_DAKOTA_CENTER = 'America/North_Dakota/Center',
	AMERICA_NORTH_DAKOTA_NEW_SALEM = 'America/North_Dakota/New_Salem',
	AMERICA_NUUK = 'America/Nuuk',
	AMERICA_OJINAGA = 'America/Ojinaga',
	AMERICA_PANAMA = 'America/Panama',
	AMERICA_PANGNIRTUNG = 'America/Pangnirtung',
	AMERICA_PARAMARIBO = 'America/Paramaribo',
	AMERICA_PHOENIX = 'America/Phoenix',
	AMERICA_PORT_AU_PRINCE = 'America/Port-au-Prince',
	AMERICA_PORT_OF_SPAIN = 'America/Port_of_Spain',
	AMERICA_PORTO_VELHO = 'America/Porto_Velho',
	AMERICA_PUERTO_RICO = 'America/Puerto_Rico',
	AMERICA_PUNTA_ARENAS = 'America/Punta_Arenas',
	AMERICA_RAINY_RIVER = 'America/Rainy_River',
	AMERICA_RANKIN_INLET = 'America/Rankin_Inlet',
	AMERICA_RECIFE = 'America/Recife',
	AMERICA_REGINA = 'America/Regina',
	AMERICA_RESOLUTE = 'America/Resolute',
	AMERICA_RIO_BRANCO = 'America/Rio_Branco',
	AMERICA_SANTAREM = 'America/Santarem',
	AMERICA_SANTIAGO = 'America/Santiago',
	AMERICA_SANTO_DOMINGO = 'America/Santo_Domingo',
	AMERICA_SAO_PAULO = 'America/Sao_Paulo',
	AMERICA_SCORESBYSUND = 'America/Scoresbysund',
	AMERICA_SITKA = 'America/Sitka',
	AMERICA_ST_BARTHELEMY = 'America/St_Barthelemy',
	AMERICA_ST_JOHNS = 'America/St_Johns',
	AMERICA_ST_KITTS = 'America/St_Kitts',
	AMERICA_ST_LUCIA = 'America/St_Lucia',
	AMERICA_ST_THOMAS = 'America/St_Thomas',
	AMERICA_ST_VINCENT = 'America/St_Vincent',
	AMERICA_SWIFT_CURRENT = 'America/Swift_Current',
	AMERICA_TEGUCIGALPA = 'America/Tegucigalpa',
	AMERICA_THULE = 'America/Thule',
	AMERICA_THUNDER_BAY = 'America/Thunder_Bay',
	AMERICA_TIJUANA = 'America/Tijuana',
	AMERICA_TORONTO = 'America/Toronto',
	AMERICA_TORTOLA = 'America/Tortola',
	AMERICA_VANCOUVER = 'America/Vancouver',
	AMERICA_WHITEHORSE = 'America/Whitehorse',
	AMERICA_WINNIPEG = 'America/Winnipeg',
	AMERICA_YAKUTAT = 'America/Yakutat',
	AMERICA_YELLOWKNIFE = 'America/Yellowknife',
	ANTARCTICA_CASEY = 'Antarctica/Casey',
	ANTARCTICA_DAVIS = 'Antarctica/Davis',
	ANTARCTICA_DUMONTDURVILLE = 'Antarctica/DumontDUrville',
	ANTARCTICA_MACQUARIE = 'Antarctica/Macquarie',
	ANTARCTICA_MAWSON = 'Antarctica/Mawson',
	ANTARCTICA_MCMURDO = 'Antarctica/McMurdo',
	ANTARCTICA_PALMER = 'Antarctica/Palmer',
	ANTARCTICA_ROTHERA = 'Antarctica/Rothera',
	ANTARCTICA_SYOWA = 'Antarctica/Syowa',
	ANTARCTICA_TROLL = 'Antarctica/Troll',
	ANTARCTICA_VOSTOK = 'Antarctica/Vostok',
	ARCTIC_LONGYEARBYEN = 'Arctic/Longyearbyen',
	ASIA_ADEN = 'Asia/Aden',
	ASIA_ALMATY = 'Asia/Almaty',
	ASIA_AMMAN = 'Asia/Amman',
	ASIA_ANADYR = 'Asia/Anadyr',
	ASIA_AQTAU = 'Asia/Aqtau',
	ASIA_AQTOBE = 'Asia/Aqtobe',
	ASIA_ASHGABAT = 'Asia/Ashgabat',
	ASIA_ATYRAU = 'Asia/Atyrau',
	ASIA_BAGHDAD = 'Asia/Baghdad',
	ASIA_BAHRAIN = 'Asia/Bahrain',
	ASIA_BAKU = 'Asia/Baku',
	ASIA_BANGKOK = 'Asia/Bangkok',
	ASIA_BARNAUL = 'Asia/Barnaul',
	ASIA_BEIRUT = 'Asia/Beirut',
	ASIA_BISHKEK = 'Asia/Bishkek',
	ASIA_BRUNEI = 'Asia/Brunei',
	ASIA_CHITA = 'Asia/Chita',
	ASIA_CHOIBALSAN = 'Asia/Choibalsan',
	ASIA_COLOMBO = 'Asia/Colombo',
	ASIA_DAMASCUS = 'Asia/Damascus',
	ASIA_DHAKA = 'Asia/Dhaka',
	ASIA_DILI = 'Asia/Dili',
	ASIA_DUBAI = 'Asia/Dubai',
	ASIA_DUSHANBE = 'Asia/Dushanbe',
	ASIA_FAMAGUSTA = 'Asia/Famagusta',
	ASIA_GAZA = 'Asia/Gaza',
	ASIA_HEBRON = 'Asia/Hebron',
	ASIA_HO_CHI_MINH = 'Asia/Ho_Chi_Minh',
	ASIA_HONG_KONG = 'Asia/Hong_Kong',
	ASIA_HOVD = 'Asia/Hovd',
	ASIA_IRKUTSK = 'Asia/Irkutsk',
	ASIA_JAKARTA = 'Asia/Jakarta',
	ASIA_JAYAPURA = 'Asia/Jayapura',
	ASIA_JERUSALEM = 'Asia/Jerusalem',
	ASIA_KABUL = 'Asia/Kabul',
	ASIA_KAMCHATKA = 'Asia/Kamchatka',
	ASIA_KARACHI = 'Asia/Karachi',
	ASIA_KATHMANDU = 'Asia/Kathmandu',
	ASIA_KHANDYGA = 'Asia/Khandyga',
	ASIA_KOLKATA = 'Asia/Kolkata',
	ASIA_KRASNOYARSK = 'Asia/Krasnoyarsk',
	ASIA_KUALA_LUMPUR = 'Asia/Kuala_Lumpur',
	ASIA_KUCHING = 'Asia/Kuching',
	ASIA_KUWAIT = 'Asia/Kuwait',
	ASIA_MACAU = 'Asia/Macau',
	ASIA_MAGADAN = 'Asia/Magadan',
	ASIA_MAKASSAR = 'Asia/Makassar',
	ASIA_MANILA = 'Asia/Manila',
	ASIA_MUSCAT = 'Asia/Muscat',
	ASIA_NICOSIA = 'Asia/Nicosia',
	ASIA_NOVOKUZNETSK = 'Asia/Novokuznetsk',
	ASIA_NOVOSIBIRSK = 'Asia/Novosibirsk',
	ASIA_OMSK = 'Asia/Omsk',
	ASIA_ORAL = 'Asia/Oral',
	ASIA_PHNOM_PENH = 'Asia/Phnom_Penh',
	ASIA_PONTIANAK = 'Asia/Pontianak',
	ASIA_PYONGYANG = 'Asia/Pyongyang',
	ASIA_QATAR = 'Asia/Qatar',
	ASIA_QOSTANAY = 'Asia/Qostanay',
	ASIA_QYZYLORDA = 'Asia/Qyzylorda',
	ASIA_RIYADH = 'Asia/Riyadh',
	ASIA_SAKHALIN = 'Asia/Sakhalin',
	ASIA_SAMARKAND = 'Asia/Samarkand',
	ASIA_SEOUL = 'Asia/Seoul',
	ASIA_SHANGHAI = 'Asia/Shanghai',
	ASIA_SINGAPORE = 'Asia/Singapore',
	ASIA_SREDNEKOLYMSK = 'Asia/Srednekolymsk',
	ASIA_TAIPEI = 'Asia/Taipei',
	ASIA_TASHKENT = 'Asia/Tashkent',
	ASIA_TBILISI = 'Asia/Tbilisi',
	ASIA_TEHRAN = 'Asia/Tehran',
	ASIA_THIMPHU = 'Asia/Thimphu',
	ASIA_TOKYO = 'Asia/Tokyo',
	ASIA_TOMSK = 'Asia/Tomsk',
	ASIA_ULAANBAATAR = 'Asia/Ulaanbaatar',
	ASIA_URUMQI = 'Asia/Urumqi',
	ASIA_UST_NERA = 'Asia/Ust-Nera',
	ASIA_VIENTIANE = 'Asia/Vientiane',
	ASIA_VLADIVOSTOK = 'Asia/Vladivostok',
	ASIA_YAKUTSK = 'Asia/Yakutsk',
	ASIA_YANGON = 'Asia/Yangon',
	ASIA_YEKATERINBURG = 'Asia/Yekaterinburg',
	ASIA_YEREVAN = 'Asia/Yerevan',
	ATLANTIC_AZORES = 'Atlantic/Azores',
	ATLANTIC_BERMUDA = 'Atlantic/Bermuda',
	ATLANTIC_CANARY = 'Atlantic/Canary',
	ATLANTIC_CAPE_VERDE = 'Atlantic/Cape_Verde',
	ATLANTIC_FAROE = 'Atlantic/Faroe',
	ATLANTIC_MADEIRA = 'Atlantic/Madeira',
	ATLANTIC_REYKJAVIK = 'Atlantic/Reykjavik',
	ATLANTIC_SOUTH_GEORGIA = 'Atlantic/South_Georgia',
	ATLANTIC_ST_HELENA = 'Atlantic/St_Helena',
	ATLANTIC_STANLEY = 'Atlantic/Stanley',
	AUSTRALIA_ADELAIDE = 'Australia/Adelaide',
	AUSTRALIA_BRISBANE = 'Australia/Brisbane',
	AUSTRALIA_BROKEN_HILL = 'Australia/Broken_Hill',
	AUSTRALIA_DARWIN = 'Australia/Darwin',
	AUSTRALIA_EUCLA = 'Australia/Eucla',
	AUSTRALIA_HOBART = 'Australia/Hobart',
	AUSTRALIA_LINDEMAN = 'Australia/Lindeman',
	AUSTRALIA_LORD_HOWE = 'Australia/Lord_Howe',
	AUSTRALIA_MELBOURNE = 'Australia/Melbourne',
	AUSTRALIA_PERTH = 'Australia/Perth',
	AUSTRALIA_SYDNEY = 'Australia/Sydney',
	EUROPE_AMSTERDAM = 'Europe/Amsterdam',
	EUROPE_ANDORRA = 'Europe/Andorra',
	EUROPE_ASTRAKHAN = 'Europe/Astrakhan',
	EUROPE_ATHENS = 'Europe/Athens',
	EUROPE_BELGRADE = 'Europe/Belgrade',
	EUROPE_BERLIN = 'Europe/Berlin',
	EUROPE_BRATISLAVA = 'Europe/Bratislava',
	EUROPE_BRUSSELS = 'Europe/Brussels',
	EUROPE_BUCHAREST = 'Europe/Bucharest',
	EUROPE_BUDAPEST = 'Europe/Budapest',
	EUROPE_BUSINGEN = 'Europe/Busingen',
	EUROPE_CHISINAU = 'Europe/Chisinau',
	EUROPE_COPENHAGEN = 'Europe/Copenhagen',
	EUROPE_DUBLIN = 'Europe/Dublin',
	EUROPE_GIBRALTAR = 'Europe/Gibraltar',
	EUROPE_GUERNSEY = 'Europe/Guernsey',
	EUROPE_HELSINKI = 'Europe/Helsinki',
	EUROPE_ISLE_OF_MAN = 'Europe/Isle_of_Man',
	EUROPE_ISTANBUL = 'Europe/Istanbul',
	EUROPE_JERSEY = 'Europe/Jersey',
	EUROPE_KALININGRAD = 'Europe/Kaliningrad',
	EUROPE_KIEV = 'Europe/Kiev',
	EUROPE_KIROV = 'Europe/Kirov',
	EUROPE_LISBON = 'Europe/Lisbon',
	EUROPE_LJUBLJANA = 'Europe/Ljubljana',
	EUROPE_LONDON = 'Europe/London',
	EUROPE_LUXEMBOURG = 'Europe/Luxembourg',
	EUROPE_MADRID = 'Europe/Madrid',
	EUROPE_MALTA = 'Europe/Malta',
	EUROPE_MARIEHAMN = 'Europe/Mariehamn',
	EUROPE_MINSK = 'Europe/Minsk',
	EUROPE_MONACO = 'Europe/Monaco',
	EUROPE_MOSCOW = 'Europe/Moscow',
	EUROPE_OSLO = 'Europe/Oslo',
	EUROPE_PARIS = 'Europe/Paris',
	EUROPE_PODGORICA = 'Europe/Podgorica',
	EUROPE_PRAGUE = 'Europe/Prague',
	EUROPE_RIGA = 'Europe/Riga',
	EUROPE_ROME = 'Europe/Rome',
	EUROPE_SAMARA = 'Europe/Samara',
	EUROPE_SAN_MARINO = 'Europe/San_Marino',
	EUROPE_SARAJEVO = 'Europe/Sarajevo',
	EUROPE_SARATOV = 'Europe/Saratov',
	EUROPE_SIMFEROPOL = 'Europe/Simferopol',
	EUROPE_SKOPJE = 'Europe/Skopje',
	EUROPE_SOFIA = 'Europe/Sofia',
	EUROPE_STOCKHOLM = 'Europe/Stockholm',
	EUROPE_TALLINN = 'Europe/Tallinn',
	EUROPE_TIRANE = 'Europe/Tirane',
	EUROPE_ULYANOVSK = 'Europe/Ulyanovsk',
	EUROPE_UZHGOROD = 'Europe/Uzhgorod',
	EUROPE_VADUZ = 'Europe/Vaduz',
	EUROPE_VATICAN = 'Europe/Vatican',
	EUROPE_VIENNA = 'Europe/Vienna',
	EUROPE_VILNIUS = 'Europe/Vilnius',
	EUROPE_VOLGOGRAD = 'Europe/Volgograd',
	EUROPE_WARSAW = 'Europe/Warsaw',
	EUROPE_ZAGREB = 'Europe/Zagreb',
	EUROPE_ZAPOROZHYE = 'Europe/Zaporozhye',
	EUROPE_ZURICH = 'Europe/Zurich',
	INDIAN_ANTANANARIVO = 'Indian/Antananarivo',
	INDIAN_CHAGOS = 'Indian/Chagos',
	INDIAN_CHRISTMAS = 'Indian/Christmas',
	INDIAN_COCOS = 'Indian/Cocos',
	INDIAN_COMORO = 'Indian/Comoro',
	INDIAN_KERGUELEN = 'Indian/Kerguelen',
	INDIAN_MAHE = 'Indian/Mahe',
	INDIAN_MALDIVES = 'Indian/Maldives',
	INDIAN_MAURITIUS = 'Indian/Mauritius',
	INDIAN_MAYOTTE = 'Indian/Mayotte',
	INDIAN_REUNION = 'Indian/Reunion',
	PACIFIC_APIA = 'Pacific/Apia',
	PACIFIC_AUCKLAND = 'Pacific/Auckland',
	PACIFIC_BOUGAINVILLE = 'Pacific/Bougainville',
	PACIFIC_CHATHAM = 'Pacific/Chatham',
	PACIFIC_CHUUK = 'Pacific/Chuuk',
	PACIFIC_EASTER = 'Pacific/Easter',
	PACIFIC_EFATE = 'Pacific/Efate',
	PACIFIC_ENDERBURY = 'Pacific/Enderbury',
	PACIFIC_FAKAOFO = 'Pacific/Fakaofo',
	PACIFIC_FIJI = 'Pacific/Fiji',
	PACIFIC_FUNAFUTI = 'Pacific/Funafuti',
	PACIFIC_GALAPAGOS = 'Pacific/Galapagos',
	PACIFIC_GAMBIER = 'Pacific/Gambier',
	PACIFIC_GUADALCANAL = 'Pacific/Guadalcanal',
	PACIFIC_GUAM = 'Pacific/Guam',
	PACIFIC_HONOLULU = 'Pacific/Honolulu',
	PACIFIC_KIRITIMATI = 'Pacific/Kiritimati',
	PACIFIC_KOSRAE = 'Pacific/Kosrae',
	PACIFIC_KWAJALEIN = 'Pacific/Kwajalein',
	PACIFIC_MAJURO = 'Pacific/Majuro',
	PACIFIC_MARQUESAS = 'Pacific/Marquesas',
	PACIFIC_MIDWAY = 'Pacific/Midway',
	PACIFIC_NAURU = 'Pacific/Nauru',
	PACIFIC_NIUE = 'Pacific/Niue',
	PACIFIC_NORFOLK = 'Pacific/Norfolk',
	PACIFIC_NOUMEA = 'Pacific/Noumea',
	PACIFIC_PAGO_PAGO = 'Pacific/Pago_Pago',
	PACIFIC_PALAU = 'Pacific/Palau',
	PACIFIC_PITCAIRN = 'Pacific/Pitcairn',
	PACIFIC_POHNPEI = 'Pacific/Pohnpei',
	PACIFIC_PORT_MORESBY = 'Pacific/Port_Moresby',
	PACIFIC_RAROTONGA = 'Pacific/Rarotonga',
	PACIFIC_SAIPAN = 'Pacific/Saipan',
	PACIFIC_TAHITI = 'Pacific/Tahiti',
	PACIFIC_TARAWA = 'Pacific/Tarawa',
	PACIFIC_TONGATAPU = 'Pacific/Tongatapu',
	PACIFIC_WAKE = 'Pacific/Wake',
	PACIFIC_WALLIS = 'Pacific/Wallis',
}

export enum LanguageTwo {
	aa = 'Afar',
	ab = 'Abkhazian',
	ae = 'Avestan',
	af = 'Afrikaans',
	ak = 'Akan',
	am = 'Amharic',
	an = 'Aragonese',
	ar = 'Arabic',
	as = 'Assamese',
	av = 'Avaric',
	ay = 'Aymara',
	az = 'Azerbaijani',
	ba = 'Bashkir',
	be = 'Belarusian',
	bg = 'Bulgarian',
	bh = 'Bihari languages',
	bi = 'Bislama',
	bm = 'Bambara',
	bn = 'Bengali',
	bo = 'Tibetan',
	br = 'Breton',
	bs = 'Bosnian',
	ca = 'Catalan; Valencian',
	ce = 'Chechen',
	ch = 'Chamorro',
	co = 'Corsican',
	cr = 'Cree',
	cs = 'Czech',
	cu = 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic',
	cv = 'Chuvash',
	cy = 'Welsh',
	da = 'Danish',
	de = 'German',
	dv = 'Divehi; Dhivehi; Maldivian',
	dz = 'Dzongkha',
	ee = 'Ewe',
	el = 'Greek, Modern (1453-)',
	en = 'English',
	eo = 'Esperanto',
	es = 'Spanish; Castilian',
	et = 'Estonian',
	eu = 'Basque',
	fa = 'Persian',
	ff = 'Fulah',
	fi = 'Finnish',
	fj = 'Fijian',
	fo = 'Faroese',
	fr = 'French',
	fy = 'Western Frisian',
	ga = 'Irish',
	gd = 'Gaelic; Scottish Gaelic',
	gl = 'Galician',
	gn = 'Guarani',
	gu = 'Gujarati',
	gv = 'Manx',
	ha = 'Hausa',
	he = 'Hebrew',
	hi = 'Hindi',
	ho = 'Hiri Motu',
	hr = 'Croatian',
	ht = 'Haitian; Haitian Creole',
	hu = 'Hungarian',
	hy = 'Armenian',
	hz = 'Herero',
	ia = 'Interlingua (International Auxiliary Language Association)',
	id = 'Indonesian',
	ie = 'Interlingue; Occidental',
	ig = 'Igbo',
	ii = 'Sichuan Yi; Nuosu',
	ik = 'Inupiaq',
	io = 'Ido',
	is = 'Icelandic',
	it = 'Italian',
	iu = 'Inuktitut',
	ja = 'Japanese',
	jv = 'Javanese',
	ka = 'Georgian',
	kg = 'Kongo',
	ki = 'Kikuyu; Gikuyu',
	kj = 'Kuanyama; Kwanyama',
	kk = 'Kazakh',
	kl = 'Kalaallisut; Greenlandic',
	km = 'Central Khmer',
	kn = 'Kannada',
	ko = 'Korean',
	kr = 'Kanuri',
	ks = 'Kashmiri',
	ku = 'Kurdish',
	kv = 'Komi',
	kw = 'Cornish',
	ky = 'Kirghiz; Kyrgyz',
	la = 'Latin',
	lb = 'Luxembourgish; Letzeburgesch',
	lg = 'Ganda',
	li = 'Limburgan; Limburger; Limburgish',
	ln = 'Lingala',
	lo = 'Lao',
	lt = 'Lithuanian',
	lu = 'Luba-Katanga',
	lv = 'Latvian',
	mg = 'Malagasy',
	mh = 'Marshallese',
	mi = 'Maori',
	mk = 'Macedonian',
	ml = 'Malayalam',
	mn = 'Mongolian',
	mr = 'Marathi',
	ms = 'Malay',
	mt = 'Maltese',
	my = 'Burmese',
	na = 'Nauru',
	nb = 'Bokmål, Norwegian; Norwegian Bokmål',
	nd = 'Ndebele, North; North Ndebele',
	ne = 'Nepali',
	ng = 'Ndonga',
	nl = 'Dutch; Flemish',
	nn = 'Norwegian Nynorsk; Nynorsk, Norwegian',
	no = 'Norwegian',
	nr = 'Ndebele, South; South Ndebele',
	nv = 'Navajo; Navaho',
	ny = 'Chichewa; Chewa; Nyanja',
	oc = 'Occitan (post 1500)',
	oj = 'Ojibwa',
	om = 'Oromo',
	or = 'Oriya',
	os = 'Ossetian; Ossetic',
	pa = 'Panjabi; Punjabi',
	pi = 'Pali',
	pl = 'Polish',
	ps = 'Pushto; Pashto',
	pt = 'Portuguese',
	qu = 'Quechua',
	rm = 'Romansh',
	rn = 'Rundi',
	ro = 'Romanian; Moldavian; Moldovan',
	ru = 'Russian',
	rw = 'Kinyarwanda',
	sa = 'Sanskrit',
	sc = 'Sardinian',
	sd = 'Sindhi',
	se = 'Northern Sami',
	sg = 'Sango',
	si = 'Sinhala; Sinhalese',
	sk = 'Slovak',
	sl = 'Slovenian',
	sm = 'Samoan',
	sn = 'Shona',
	so = 'Somali',
	sq = 'Albanian',
	sr = 'Serbian',
	ss = 'Swati',
	st = 'Sotho, Southern',
	su = 'Sundanese',
	sv = 'Swedish',
	sw = 'Swahili',
	ta = 'Tamil',
	te = 'Telugu',
	tg = 'Tajik',
	th = 'Thai',
	ti = 'Tigrinya',
	tk = 'Turkmen',
	tl = 'Tagalog',
	tn = 'Tswana',
	to = 'Tonga (Tonga Islands)',
	tr = 'Turkish',
	ts = 'Tsonga',
	tt = 'Tatar',
	tw = 'Twi',
	ty = 'Tahitian',
	ug = 'Uighur; Uyghur',
	uk = 'Ukrainian',
	ur = 'Urdu',
	uz = 'Uzbek',
	ve = 'Venda',
	vi = 'Vietnamese',
	vo = 'Volapük',
	wa = 'Walloon',
	wo = 'Wolof',
	xh = 'Xhosa',
	yi = 'Yiddish',
	yo = 'Yoruba',
	za = 'Zhuang; Chuang',
	zh = 'Chinese',
	zu = 'Zulu',
}

export enum LanguageThree {
	aar = 'Afar',
	abk = 'Abkhazian',
	ace = 'Achinese',
	ach = 'Acoli',
	ada = 'Adangme',
	ady = 'Adyghe; Adygei',
	afa = 'Afro-Asiatic languages',
	afh = 'Afrihili',
	afr = 'Afrikaans',
	ain = 'Ainu',
	aka = 'Akan',
	akk = 'Akkadian',
	alb = 'Albanian',
	ale = 'Aleut',
	alg = 'Algonquian languages',
	alt = 'Southern Altai',
	amh = 'Amharic',
	ang = 'English, Old (ca.450-1100)',
	anp = 'Angika',
	apa = 'Apache languages',
	ara = 'Arabic',
	arc = 'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)',
	arg = 'Aragonese',
	arm = 'Armenian',
	arn = 'Mapudungun; Mapuche',
	arp = 'Arapaho',
	art = 'Artificial languages',
	arw = 'Arawak',
	asm = 'Assamese',
	ast = 'Asturian; Bable; Leonese; Asturleonese',
	ath = 'Athapascan languages',
	aus = 'Australian languages',
	ava = 'Avaric',
	ave = 'Avestan',
	awa = 'Awadhi',
	aym = 'Aymara',
	aze = 'Azerbaijani',
	bad = 'Banda languages',
	bai = 'Bamileke languages',
	bak = 'Bashkir',
	bal = 'Baluchi',
	bam = 'Bambara',
	ban = 'Balinese',
	baq = 'Basque',
	bas = 'Basa',
	bat = 'Baltic languages',
	bej = 'Beja; Bedawiyet',
	bel = 'Belarusian',
	bem = 'Bemba',
	ben = 'Bengali',
	ber = 'Berber languages',
	bho = 'Bhojpuri',
	bih = 'Bihari languages',
	bik = 'Bikol',
	bin = 'Bini; Edo',
	bis = 'Bislama',
	bla = 'Siksika',
	bnt = 'Bantu languages',
	bod = 'Tibetan',
	bos = 'Bosnian',
	bra = 'Braj',
	bre = 'Breton',
	btk = 'Batak languages',
	bua = 'Buriat',
	bug = 'Buginese',
	bul = 'Bulgarian',
	bur = 'Blin; Bilin; Burmese',
	byn = 'Blin; Bilin',
	cad = 'Caddo',
	cai = 'Central American Indian languages',
	car = 'Galibi Carib',
	cat = 'Catalan; Valencian',
	cau = 'Caucasian languages',
	ceb = 'Cebuano',
	cel = 'Celtic languages',
	ces = 'Czech',
	cha = 'Chamorro',
	chb = 'Chibcha',
	che = 'Chechen',
	chg = 'Chagatai',
	chi = 'Chinese',
	chk = 'Chuukese',
	chm = 'Mari',
	chn = 'Chinook jargon',
	cho = 'Choctaw',
	chp = 'Chipewyan; Dene Suline',
	chr = 'Cherokee',
	chu = 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic',
	chv = 'Chuvash',
	chy = 'Cheyenne',
	cmc = 'Chamic languages',
	cnr = 'Montenegrin',
	cop = 'Coptic',
	cor = 'Cornish',
	cos = 'Corsican',
	cpe = 'Creoles and pidgins, English based',
	cpf = 'Creoles and pidgins, French-based',
	cpp = 'Creoles and pidgins, Portuguese-based',
	cre = 'Cree',
	crh = 'Crimean Tatar; Crimean Turkish',
	crp = 'Creoles and pidgins',
	csb = 'Kashubian',
	cus = 'Cushitic languages',
	cym = 'Welsh',
	cze = 'Czech',
	dak = 'Dakota',
	dan = 'Danish',
	dar = 'Dargwa',
	day = 'Land Dayak languages',
	del = 'Delaware',
	den = 'Slave (Athapascan)',
	deu = 'German',
	dgr = 'Dogrib',
	din = 'Dinka',
	div = 'Divehi; Dhivehi; Maldivian',
	doi = 'Dogri',
	dra = 'Dravidian languages',
	dsb = 'Lower Sorbian',
	dua = 'Duala',
	dum = 'Dutch, Middle (ca.1050-1350)',
	dut = 'Dutch; Flemish',
	dyu = 'Dyula',
	dzo = 'Dzongkha',
	efi = 'Efik',
	egy = 'Egyptian (Ancient)',
	eka = 'Ekajuk',
	ell = 'Greek, Modern (1453-)',
	elx = 'Elamite',
	eng = 'English',
	enm = 'English, Middle (1100-1500)',
	epo = 'Esperanto',
	est = 'Estonian',
	eus = 'Basque',
	ewe = 'Ewe',
	ewo = 'Ewondo',
	fan = 'Fang',
	fao = 'Faroese',
	fas = 'Persian',
	fat = 'Fanti',
	fij = 'Fijian',
	fil = 'Filipino; Pilipino',
	fin = 'Finnish',
	fiu = 'Finno-Ugrian languages',
	fon = 'Fon',
	fra = 'French',
	fre = 'French',
	frm = 'French, Middle (ca.1400-1600)',
	fro = 'French, Old (842-ca.1400)',
	frr = 'Northern Frisian',
	frs = 'Eastern Frisian',
	fry = 'Western Frisian',
	ful = 'Fulah',
	fur = 'Friulian',
	gaa = 'Ga',
	gay = 'Gayo',
	gba = 'Gbaya',
	gem = 'Germanic languages',
	geo = 'Georgian',
	ger = 'German',
	gez = 'Geez',
	gil = 'Gilbertese',
	gla = 'Gaelic; Scottish Gaelic',
	gle = 'Irish',
	glg = 'Galician',
	glv = 'Manx',
	gmh = 'German, Middle High (ca.1050-1500)',
	goh = 'German, Old High (ca.750-1050)',
	gon = 'Gondi',
	gor = 'Gorontalo',
	got = 'Gothic',
	grb = 'Grebo',
	grc = 'Greek, Ancient (to 1453)',
	gre = 'Greek, Modern (1453-)',
	grn = 'Guarani',
	gsw = 'Swiss German; Alemannic; Alsatian',
	guj = 'Gujarati',
	gwi = 'Gwich&apos;in',
	hai = 'Haida',
	hat = 'Haitian; Haitian Creole',
	hau = 'Hausa',
	haw = 'Hawaiian',
	heb = 'Hebrew',
	her = 'Herero',
	hil = 'Hiligaynon',
	him = 'Himachali languages; Western Pahari languages',
	hin = 'Hindi',
	hit = 'Hittite',
	hmn = 'Hmong; Mong',
	hmo = 'Hiri Motu',
	hrv = 'Croatian',
	hsb = 'Upper Sorbian',
	hun = 'Hungarian',
	hup = 'Hupa',
	hye = 'Armenian',
	iba = 'Iban',
	ibo = 'Igbo',
	ice = 'Icelandic',
	ido = 'Ido',
	iii = 'Sichuan Yi; Nuosu',
	ijo = 'Ijo languages',
	iku = 'Inuktitut',
	ile = 'Interlingue; Occidental',
	ilo = 'Iloko',
	ina = 'Interlingua (International Auxiliary Language Association)',
	inc = 'Indic languages',
	ind = 'Indonesian',
	ine = 'Indo-European languages',
	inh = 'Ingush',
	ipk = 'Inupiaq',
	ira = 'Iranian languages',
	iro = 'Iroquoian languages',
	isl = 'Icelandic',
	ita = 'Italian',
	jav = 'Javanese',
	jbo = 'Lojban',
	jpn = 'Japanese',
	jpr = 'Judeo-Persian',
	jrb = 'Judeo-Arabic',
	kaa = 'Kara-Kalpak',
	kab = 'Kabyle',
	kac = 'Kachin; Jingpho',
	kal = 'Kalaallisut; Greenlandic',
	kam = 'Kamba',
	kan = 'Kannada',
	kar = 'Karen languages',
	kas = 'Kashmiri',
	kat = 'Georgian',
	kau = 'Kanuri',
	kaw = 'Kawi',
	kaz = 'Kazakh',
	kbd = 'Kabardian',
	kha = 'Khasi',
	khi = 'Khoisan languages',
	khm = 'Central Khmer',
	kho = 'Khotanese; Sakan',
	kik = 'Kikuyu; Gikuyu',
	kin = 'Kinyarwanda',
	kir = 'Kirghiz; Kyrgyz',
	kmb = 'Kimbundu',
	kok = 'Konkani',
	kom = 'Komi',
	kon = 'Kongo',
	kor = 'Korean',
	kos = 'Kosraean',
	kpe = 'Kpelle',
	krc = 'Karachay-Balkar',
	krl = 'Karelian',
	kro = 'Kru languages',
	kru = 'Kurukh',
	kua = 'Kuanyama; Kwanyama',
	kum = 'Kumyk',
	kur = 'Kurdish',
	kut = 'Kutenai',
	lad = 'Ladino',
	lah = 'Lahnda',
	lam = 'Lamba',
	lao = 'Lao',
	lat = 'Latin',
	lav = 'Latvian',
	lez = 'Lezghian',
	lim = 'Limburgan; Limburger; Limburgish',
	lin = 'Lingala',
	lit = 'Lithuanian',
	lol = 'Mongo',
	loz = 'Lozi',
	ltz = 'Luxembourgish; Letzeburgesch',
	lua = 'Luba-Lulua',
	lub = 'Luba-Katanga',
	lug = 'Ganda',
	lui = 'Luiseno',
	lun = 'Lunda',
	luo = 'Luo (Kenya and Tanzania)',
	lus = 'Lushai',
	mac = 'Macedonian',
	mad = 'Madurese',
	mag = 'Magahi',
	mah = 'Marshallese',
	mai = 'Maithili',
	mak = 'Makasar',
	mal = 'Malayalam',
	man = 'Mandingo',
	mao = 'Maori',
	map = 'Austronesian languages',
	mar = 'Marathi',
	mas = 'Masai',
	may = 'Malay',
	mdf = 'Moksha',
	mdr = 'Mandar',
	men = 'Mende',
	mga = 'Irish, Middle (900-1200)',
	mic = 'Mi&apos;kmaq; Micmac',
	min = 'Minangkabau',
	mis = 'Uncoded languages',
	mkd = 'Macedonian',
	mkh = 'Mon-Khmer languages',
	mlg = 'Malagasy',
	mlt = 'Maltese',
	mnc = 'Manchu',
	mni = 'Manipuri',
	mno = 'Manobo languages',
	moh = 'Mohawk',
	mon = 'Mongolian',
	mos = 'Mossi',
	mri = 'Maori',
	msa = 'Malay',
	mul = 'Multiple languages',
	mun = 'Munda languages',
	mus = 'Creek',
	mwl = 'Mirandese',
	mwr = 'Marwari',
	mya = 'Blin; Bilin; Burmese',
	myn = 'Mayan languages',
	myv = 'Erzya',
	nah = 'Nahuatl languages',
	nai = 'North American Indian languages',
	nap = 'Neapolitan',
	nau = 'Nauru',
	nav = 'Navajo; Navaho',
	nbl = 'Ndebele, South; South Ndebele',
	nde = 'Ndebele, North; North Ndebele',
	ndo = 'Ndonga',
	nds = 'Low German; Low Saxon; German, Low; Saxon, Low',
	nep = 'Nepali',
	new = 'Nepal Bhasa; Newari',
	nia = 'Nias',
	nic = 'Niger-Kordofanian languages',
	niu = 'Niuean',
	nld = 'Dutch; Flemish',
	nno = 'Norwegian Nynorsk; Nynorsk, Norwegian',
	nob = 'Bokmål, Norwegian; Norwegian Bokmål',
	nog = 'Nogai',
	non = 'Norse, Old',
	nor = 'Norwegian',
	nqo = 'N&apos;Ko',
	nso = 'Pedi; Sepedi; Northern Sotho',
	nub = 'Nubian languages',
	nwc = 'Classical Newari; Old Newari; Classical Nepal Bhasa',
	nya = 'Chichewa; Chewa; Nyanja',
	nym = 'Nyamwezi',
	nyn = 'Nyankole',
	nyo = 'Nyoro',
	nzi = 'Nzima',
	oci = 'Occitan (post 1500)',
	oji = 'Ojibwa',
	ori = 'Oriya',
	orm = 'Oromo',
	osa = 'Osage',
	oss = 'Ossetian; Ossetic',
	ota = 'Turkish, Ottoman (1500-1928)',
	oto = 'Otomian languages',
	paa = 'Papuan languages',
	pag = 'Pangasinan',
	pal = 'Pahlavi',
	pam = 'Pampanga; Kapampangan',
	pan = 'Panjabi; Punjabi',
	pap = 'Papiamento',
	pau = 'Palauan',
	peo = 'Persian, Old (ca.600-400 B.C.)',
	per = 'Persian',
	phi = 'Philippine languages',
	phn = 'Phoenician',
	pli = 'Pali',
	pol = 'Polish',
	pon = 'Pohnpeian',
	por = 'Portuguese',
	pra = 'Prakrit languages',
	pro = 'Provençal, Old (to 1500);Occitan, Old (to 1500)',
	pus = 'Pushto; Pashto',
	que = 'Quechua',
	raj = 'Rajasthani',
	rap = 'Rapanui',
	rar = 'Rarotongan; Cook Islands Maori',
	roa = 'Romance languages',
	roh = 'Romansh',
	rom = 'Romany',
	ron = 'Romanian; Moldavian; Moldovan',
	rum = 'Romanian; Moldavian; Moldovan',
	run = 'Rundi',
	rup = 'Aromanian; Arumanian; Macedo-Romanian',
	rus = 'Russian',
	sad = 'Sandawe',
	sag = 'Sango',
	sah = 'Yakut',
	sai = 'South American Indian languages',
	sal = 'Salishan languages',
	sam = 'Samaritan Aramaic',
	san = 'Sanskrit',
	sas = 'Sasak',
	sat = 'Santali',
	scn = 'Sicilian',
	sco = 'Scots',
	sel = 'Selkup',
	sem = 'Semitic languages',
	sga = 'Irish, Old (to 900)',
	sgn = 'Sign Languages',
	shn = 'Shan',
	sid = 'Sidamo',
	sin = 'Sinhala; Sinhalese',
	sio = 'Siouan languages',
	sit = 'Sino-Tibetan languages',
	sla = 'Slavic languages',
	slk = 'Slovak',
	slo = 'Slovak',
	slv = 'Slovenian',
	sma = 'Southern Sami',
	sme = 'Northern Sami',
	smi = 'Sami languages',
	smj = 'Lule Sami',
	smn = 'Inari Sami',
	smo = 'Samoan',
	sms = 'Skolt Sami',
	sna = 'Shona',
	snd = 'Sindhi',
	snk = 'Soninke',
	sog = 'Sogdian',
	som = 'Somali',
	son = 'Songhai languages',
	sot = 'Sotho, Southern',
	spa = 'Spanish; Castilian',
	sqi = 'Albanian',
	srd = 'Sardinian',
	srn = 'Sranan Tongo',
	srp = 'Serbian',
	srr = 'Serer',
	ssa = 'Nilo-Saharan languages',
	ssw = 'Swati',
	suk = 'Sukuma',
	sun = 'Sundanese',
	sus = 'Susu',
	sux = 'Sumerian',
	swa = 'Swahili',
	swe = 'Swedish',
	syc = 'Classical Syriac',
	syr = 'Syriac',
	tah = 'Tahitian',
	tai = 'Tai languages',
	tam = 'Tamil',
	tat = 'Tatar',
	tel = 'Telugu',
	tem = 'Timne',
	ter = 'Tereno',
	tet = 'Tetum',
	tgk = 'Tajik',
	tgl = 'Tagalog',
	tha = 'Thai',
	tib = 'Tibetan',
	tig = 'Tigre',
	tir = 'Tigrinya',
	tiv = 'Tiv',
	tkl = 'Tokelau',
	tlh = 'Klingon; tlhIngan-Hol',
	tli = 'Tlingit',
	tmh = 'Tamashek',
	tog = 'Tonga (Nyasa)',
	ton = 'Tonga (Tonga Islands)',
	tpi = 'Tok Pisin',
	tsi = 'Tsimshian',
	tsn = 'Tswana',
	tso = 'Tsonga',
	tuk = 'Turkmen',
	tum = 'Tumbuka',
	tup = 'Tupi languages',
	tur = 'Turkish',
	tut = 'Altaic languages',
	tvl = 'Tuvalu',
	twi = 'Twi',
	tyv = 'Tuvinian',
	udm = 'Udmurt',
	uga = 'Ugaritic',
	uig = 'Uighur; Uyghur',
	ukr = 'Ukrainian',
	umb = 'Umbundu',
	und = 'Undetermined',
	urd = 'Urdu',
	uzb = 'Uzbek',
	vai = 'Vai',
	ven = 'Venda',
	vie = 'Vietnamese',
	vol = 'Volapük',
	vot = 'Votic',
	wak = 'Wakashan languages',
	wal = 'Wolaitta; Wolaytta',
	war = 'Waray',
	was = 'Washo',
	wel = 'Welsh',
	wen = 'Sorbian languages',
	wln = 'Walloon',
	wol = 'Wolof',
	xal = 'Kalmyk; Oirat',
	xho = 'Xhosa',
	yao = 'Yao',
	yap = 'Yapese',
	yid = 'Yiddish',
	yor = 'Yoruba',
	ypk = 'Yupik languages',
	zap = 'Zapotec',
	zbl = 'Blissymbols; Blissymbolics; Bliss',
	zen = 'Zenaga',
	zgh = 'Standard Moroccan Tamazight',
	zha = 'Zhuang; Chuang',
	zho = 'Chinese',
	znd = 'Zande languages',
	zul = 'Zulu',
	zun = 'Zuni',
	zxx = 'No linguistic content; Not applicable',
	zza = 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki',
}

export enum KeyboardKey {
	Control = 'Ctrl',
	Shift = 'Shift',
	Alt = 'Alt',
	Command = '⌘',
	Home = 'Home',
	End = 'End',
	Tab = 'Tab',
	Windows = 'Win',
	Pause = 'Pause',
	Break = 'Break',
	PageUp = 'PageUp',
	PageDown = 'PageDn',
	PrintScreen = 'PrtSc',
	ScrollLock = 'ScrollLock',
	Backspace = 'Backspace',
	Delele = 'Del',
	Insert = 'Ins',
	Escape = 'Esc',
	F1 = 'F1',
	F2 = 'F2',
	F3 = 'F3',
	F4 = 'F4',
	F5 = 'F5',
	F6 = 'F6',
	F7 = 'F7',
	F8 = 'F8',
	F9 = 'F9',
	F10 = 'F10',
	F11 = 'F11',
	F12 = 'F12',
	One = '1',
	Two = '2',
	Three = '3',
	Four = '4',
	Five = '5',
	Six = '6',
	Seven = '7',
	Eight = '8',
	Nine = '9',
	Zero = '0',
	A = 'A',
	B = 'B',
	C = 'C',
	D = 'D',
	E = 'E',
	F = 'F',
	G = 'G',
	H = 'H',
	I = 'I',
	J = 'J',
	K = 'K',
	L = 'L',
	M = 'M',
	N = 'N',
	O = 'O',
	P = 'P',
	Q = 'Q',
	R = 'R',
	S = 'S',
	T = 'T',
	U = 'U',
	V = 'V',
	W = 'W',
	X = 'X',
	Y = 'Y',
	Z = 'Z',
	BackTick = '`',
	Hyphen = '-',
	Equals = '=',
	OpenBracket = '[',
	CloseBracket = ']',
	Backslash = '\\',
	Semicolon = ';',
	Apostrophe = "'",
	Comma = ',',
	Period = '.',
	Slash = '/',
	ArrowLeft = '←',
	ArrowRight = '→',
	ArrowUp = '↑',
	ArrowDown = '↓',
}
